package tecmides;

public enum MiningAttribute {
    GRADE,
    Q_ASSIGN_VIEW, 
    Q_ASSIGN_SUBMIT,
    Q_FORUM_CREATE,
    Q_FORUM_GROUP_ACCESS,
    Q_FORUM_DISCUSSION_ACCESS,
    Q_RESOURCE_VIEW,
    ST_INDIV_ASSIGN_LTSUBMIT,
    ST_GROUP_ASSIGN_LTSUBMIT,
    ST_INDIV_SUBJECT_DIFF,
    RC_INDIV_ASSIGN_LTSUBMIT,
    RC_GROUP_ASSIGN_LTSUBMIT,
    RC_INDIV_SUBJECT_KEEPUP,
    RC_INDIV_SUBJECT_DIFF;
    
}
